// Generated by gencpp from file rm_msgs/Arm_Software_Version.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_ARM_SOFTWARE_VERSION_H
#define RM_MSGS_MESSAGE_ARM_SOFTWARE_VERSION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rm_msgs/Softwarebuildinfo.h>
#include <rm_msgs/Softwarebuildinfo.h>
#include <rm_msgs/Softwarebuildinfo.h>
#include <rm_msgs/Softwarebuildinfo.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct Arm_Software_Version_
{
  typedef Arm_Software_Version_<ContainerAllocator> Type;

  Arm_Software_Version_()
    : product_version()
    , algorithm_info()
    , ctrl_info()
    , dynamic_info()
    , plan_info()
    , controller_version()
    , com_info()
    , program_info()  {
    }
  Arm_Software_Version_(const ContainerAllocator& _alloc)
    : product_version(_alloc)
    , algorithm_info(_alloc)
    , ctrl_info(_alloc)
    , dynamic_info(_alloc)
    , plan_info(_alloc)
    , controller_version(_alloc)
    , com_info(_alloc)
    , program_info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _product_version_type;
  _product_version_type product_version;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _algorithm_info_type;
  _algorithm_info_type algorithm_info;

   typedef  ::rm_msgs::Softwarebuildinfo_<ContainerAllocator>  _ctrl_info_type;
  _ctrl_info_type ctrl_info;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dynamic_info_type;
  _dynamic_info_type dynamic_info;

   typedef  ::rm_msgs::Softwarebuildinfo_<ContainerAllocator>  _plan_info_type;
  _plan_info_type plan_info;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _controller_version_type;
  _controller_version_type controller_version;

   typedef  ::rm_msgs::Softwarebuildinfo_<ContainerAllocator>  _com_info_type;
  _com_info_type com_info;

   typedef  ::rm_msgs::Softwarebuildinfo_<ContainerAllocator>  _program_info_type;
  _program_info_type program_info;





  typedef boost::shared_ptr< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_Software_Version_

typedef ::rm_msgs::Arm_Software_Version_<std::allocator<void> > Arm_Software_Version;

typedef boost::shared_ptr< ::rm_msgs::Arm_Software_Version > Arm_Software_VersionPtr;
typedef boost::shared_ptr< ::rm_msgs::Arm_Software_Version const> Arm_Software_VersionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Arm_Software_Version_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Arm_Software_Version_<ContainerAllocator1> & lhs, const ::rm_msgs::Arm_Software_Version_<ContainerAllocator2> & rhs)
{
  return lhs.product_version == rhs.product_version &&
    lhs.algorithm_info == rhs.algorithm_info &&
    lhs.ctrl_info == rhs.ctrl_info &&
    lhs.dynamic_info == rhs.dynamic_info &&
    lhs.plan_info == rhs.plan_info &&
    lhs.controller_version == rhs.controller_version &&
    lhs.com_info == rhs.com_info &&
    lhs.program_info == rhs.program_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Arm_Software_Version_<ContainerAllocator1> & lhs, const ::rm_msgs::Arm_Software_Version_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f90eb6551bbde202ac1756e5a3ee2f6d";
  }

  static const char* value(const ::rm_msgs::Arm_Software_Version_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf90eb6551bbde202ULL;
  static const uint64_t static_value2 = 0xac1756e5a3ee2f6dULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Arm_Software_Version";
  }

  static const char* value(const ::rm_msgs::Arm_Software_Version_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string product_version\n"
"string algorithm_info\n"
"Softwarebuildinfo ctrl_info\n"
"string dynamic_info #3\n"
"Softwarebuildinfo plan_info #3\n"
"string controller_version #4\n"
"Softwarebuildinfo com_info #4\n"
"Softwarebuildinfo program_info #4\n"
"================================================================================\n"
"MSG: rm_msgs/Softwarebuildinfo\n"
"string build_time\n"
"string version\n"
;
  }

  static const char* value(const ::rm_msgs::Arm_Software_Version_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.product_version);
      stream.next(m.algorithm_info);
      stream.next(m.ctrl_info);
      stream.next(m.dynamic_info);
      stream.next(m.plan_info);
      stream.next(m.controller_version);
      stream.next(m.com_info);
      stream.next(m.program_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Arm_Software_Version_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Arm_Software_Version_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Arm_Software_Version_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "product_version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.product_version);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "algorithm_info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.algorithm_info);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ctrl_info: ";
    Printer< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >::stream(s, indent + "  ", v.ctrl_info);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dynamic_info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dynamic_info);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "plan_info: ";
    Printer< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >::stream(s, indent + "  ", v.plan_info);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "controller_version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.controller_version);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "com_info: ";
    Printer< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >::stream(s, indent + "  ", v.com_info);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "program_info: ";
    Printer< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >::stream(s, indent + "  ", v.program_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_ARM_SOFTWARE_VERSION_H
