// Generated by gencpp from file rm_msgs/ExpandState.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_EXPANDSTATE_H
#define RM_MSGS_MESSAGE_EXPANDSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct ExpandState_
{
  typedef ExpandState_<ContainerAllocator> Type;

  ExpandState_()
    : get_state(false)
    , pos(0)
    , err_flag(0)
    , en_flag(0)
    , current(0)
    , mode(0)
    , joint_id(0)  {
    }
  ExpandState_(const ContainerAllocator& _alloc)
    : get_state(false)
    , pos(0)
    , err_flag(0)
    , en_flag(0)
    , current(0)
    , mode(0)
    , joint_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _get_state_type;
  _get_state_type get_state;

   typedef int16_t _pos_type;
  _pos_type pos;

   typedef int16_t _err_flag_type;
  _err_flag_type err_flag;

   typedef uint16_t _en_flag_type;
  _en_flag_type en_flag;

   typedef uint16_t _current_type;
  _current_type current;

   typedef int8_t _mode_type;
  _mode_type mode;

   typedef uint16_t _joint_id_type;
  _joint_id_type joint_id;





  typedef boost::shared_ptr< ::rm_msgs::ExpandState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::ExpandState_<ContainerAllocator> const> ConstPtr;

}; // struct ExpandState_

typedef ::rm_msgs::ExpandState_<std::allocator<void> > ExpandState;

typedef boost::shared_ptr< ::rm_msgs::ExpandState > ExpandStatePtr;
typedef boost::shared_ptr< ::rm_msgs::ExpandState const> ExpandStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::ExpandState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::ExpandState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::ExpandState_<ContainerAllocator1> & lhs, const ::rm_msgs::ExpandState_<ContainerAllocator2> & rhs)
{
  return lhs.get_state == rhs.get_state &&
    lhs.pos == rhs.pos &&
    lhs.err_flag == rhs.err_flag &&
    lhs.en_flag == rhs.en_flag &&
    lhs.current == rhs.current &&
    lhs.mode == rhs.mode &&
    lhs.joint_id == rhs.joint_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::ExpandState_<ContainerAllocator1> & lhs, const ::rm_msgs::ExpandState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ExpandState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ExpandState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ExpandState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ExpandState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ExpandState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ExpandState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::ExpandState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51186bb81aaa7ad5c549fa4631da2340";
  }

  static const char* value(const ::rm_msgs::ExpandState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51186bb81aaa7ad5ULL;
  static const uint64_t static_value2 = 0xc549fa4631da2340ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::ExpandState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/ExpandState";
  }

  static const char* value(const ::rm_msgs::ExpandState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::ExpandState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool get_state\n"
"int16 pos	    #扩展关节角度，单位度，精度 0.001°\n"
"int16 err_flag	#驱动错误代码\n"
"uint16 en_flag	#扩展关节使能状态\n"
"uint16 current	#当前驱动电流，单位：mA，精度：1mA。\n"
"byte mode	    #当前扩展关节状态，0-空闲，1-正方向速度运动，2-正方向位置运动，3-负方向速度运动，4-负方向位置运动\n"
"uint16 joint_id	#扩展关节ID\n"
;
  }

  static const char* value(const ::rm_msgs::ExpandState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::ExpandState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get_state);
      stream.next(m.pos);
      stream.next(m.err_flag);
      stream.next(m.en_flag);
      stream.next(m.current);
      stream.next(m.mode);
      stream.next(m.joint_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExpandState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::ExpandState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::ExpandState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "get_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "err_flag: ";
    Printer<int16_t>::stream(s, indent + "  ", v.err_flag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "en_flag: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.en_flag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.current);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.joint_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_EXPANDSTATE_H
