// Generated by gencpp from file rm_msgs/Expand_Position.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_EXPAND_POSITION_H
#define RM_MSGS_MESSAGE_EXPAND_POSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Expand_Position_
{
  typedef Expand_Position_<ContainerAllocator> Type;

  Expand_Position_()
    : pos(0)
    , speed(0)  {
    }
  Expand_Position_(const ContainerAllocator& _alloc)
    : pos(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef int16_t _pos_type;
  _pos_type pos;

   typedef int16_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::rm_msgs::Expand_Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Expand_Position_<ContainerAllocator> const> ConstPtr;

}; // struct Expand_Position_

typedef ::rm_msgs::Expand_Position_<std::allocator<void> > Expand_Position;

typedef boost::shared_ptr< ::rm_msgs::Expand_Position > Expand_PositionPtr;
typedef boost::shared_ptr< ::rm_msgs::Expand_Position const> Expand_PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Expand_Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Expand_Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Expand_Position_<ContainerAllocator1> & lhs, const ::rm_msgs::Expand_Position_<ContainerAllocator2> & rhs)
{
  return lhs.pos == rhs.pos &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Expand_Position_<ContainerAllocator1> & lhs, const ::rm_msgs::Expand_Position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Expand_Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Expand_Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Expand_Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Expand_Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Expand_Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Expand_Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Expand_Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "464e5f6ba74ca32e53b631f4eeffd5ab";
  }

  static const char* value(const ::rm_msgs::Expand_Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x464e5f6ba74ca32eULL;
  static const uint64_t static_value2 = 0x53b631f4eeffd5abULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Expand_Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Expand_Position";
  }

  static const char* value(const ::rm_msgs::Expand_Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Expand_Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 pos        #扩展关节位置，单位 \n"
"int16 speed         #速度百分比，1~100\n"
;
  }

  static const char* value(const ::rm_msgs::Expand_Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Expand_Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Expand_Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Expand_Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Expand_Position_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pos: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_EXPAND_POSITION_H
