// Generated by gencpp from file rm_msgs/Flowchartrunstate.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_FLOWCHARTRUNSTATE_H
#define RM_MSGS_MESSAGE_FLOWCHARTRUNSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Flowchartrunstate_
{
  typedef Flowchartrunstate_<ContainerAllocator> Type;

  Flowchartrunstate_()
    : run_state(0)
    , id(0)
    , name()
    , plan_speed(0)
    , step_mode(0)
    , modal_id()  {
    }
  Flowchartrunstate_(const ContainerAllocator& _alloc)
    : run_state(0)
    , id(0)
    , name(_alloc)
    , plan_speed(0)
    , step_mode(0)
    , modal_id(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _run_state_type;
  _run_state_type run_state;

   typedef uint8_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _plan_speed_type;
  _plan_speed_type plan_speed;

   typedef uint8_t _step_mode_type;
  _step_mode_type step_mode;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _modal_id_type;
  _modal_id_type modal_id;





  typedef boost::shared_ptr< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> const> ConstPtr;

}; // struct Flowchartrunstate_

typedef ::rm_msgs::Flowchartrunstate_<std::allocator<void> > Flowchartrunstate;

typedef boost::shared_ptr< ::rm_msgs::Flowchartrunstate > FlowchartrunstatePtr;
typedef boost::shared_ptr< ::rm_msgs::Flowchartrunstate const> FlowchartrunstateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Flowchartrunstate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Flowchartrunstate_<ContainerAllocator1> & lhs, const ::rm_msgs::Flowchartrunstate_<ContainerAllocator2> & rhs)
{
  return lhs.run_state == rhs.run_state &&
    lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.plan_speed == rhs.plan_speed &&
    lhs.step_mode == rhs.step_mode &&
    lhs.modal_id == rhs.modal_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Flowchartrunstate_<ContainerAllocator1> & lhs, const ::rm_msgs::Flowchartrunstate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05f1a2e93a88cd1e5f9f80d8af8e987a";
  }

  static const char* value(const ::rm_msgs::Flowchartrunstate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05f1a2e93a88cd1eULL;
  static const uint64_t static_value2 = 0x5f9f80d8af8e987aULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Flowchartrunstate";
  }

  static const char* value(const ::rm_msgs::Flowchartrunstate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 run_state  # 运行状态 0 未开始 1运行中 2暂停中\n"
"uint8 id         # 当前使能的文件id。\n"
"string name # 当前使能的文件名称。\n"
"uint8 plan_speed     # 当前使能的文件全局规划速度比例 1-100。\n"
"uint8 step_mode    # 单步模式，0为空，1为正常, 2为单步。\n"
"string modal_id   # 运行到的流程图块的id。未运行则不返回\n"
;
  }

  static const char* value(const ::rm_msgs::Flowchartrunstate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.run_state);
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.plan_speed);
      stream.next(m.step_mode);
      stream.next(m.modal_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Flowchartrunstate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Flowchartrunstate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Flowchartrunstate_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "run_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "plan_speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "step_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.step_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "modal_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.modal_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_FLOWCHARTRUNSTATE_H
