// Generated by gencpp from file rm_msgs/Gettrajectorylist.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_GETTRAJECTORYLIST_H
#define RM_MSGS_MESSAGE_GETTRAJECTORYLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Gettrajectorylist_
{
  typedef Gettrajectorylist_<ContainerAllocator> Type;

  Gettrajectorylist_()
    : page_num(0)
    , page_size(0)
    , vague_search()  {
    }
  Gettrajectorylist_(const ContainerAllocator& _alloc)
    : page_num(0)
    , page_size(0)
    , vague_search(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _page_num_type;
  _page_num_type page_num;

   typedef int32_t _page_size_type;
  _page_size_type page_size;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _vague_search_type;
  _vague_search_type vague_search;





  typedef boost::shared_ptr< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> const> ConstPtr;

}; // struct Gettrajectorylist_

typedef ::rm_msgs::Gettrajectorylist_<std::allocator<void> > Gettrajectorylist;

typedef boost::shared_ptr< ::rm_msgs::Gettrajectorylist > GettrajectorylistPtr;
typedef boost::shared_ptr< ::rm_msgs::Gettrajectorylist const> GettrajectorylistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Gettrajectorylist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Gettrajectorylist_<ContainerAllocator1> & lhs, const ::rm_msgs::Gettrajectorylist_<ContainerAllocator2> & rhs)
{
  return lhs.page_num == rhs.page_num &&
    lhs.page_size == rhs.page_size &&
    lhs.vague_search == rhs.vague_search;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Gettrajectorylist_<ContainerAllocator1> & lhs, const ::rm_msgs::Gettrajectorylist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbe34dfd8b66421bedf70042e463f5a2";
  }

  static const char* value(const ::rm_msgs::Gettrajectorylist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbe34dfd8b66421bULL;
  static const uint64_t static_value2 = 0xedf70042e463f5a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Gettrajectorylist";
  }

  static const char* value(const ::rm_msgs::Gettrajectorylist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 page_num\n"
"int32 page_size\n"
"string vague_search\n"
;
  }

  static const char* value(const ::rm_msgs::Gettrajectorylist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.page_num);
      stream.next(m.page_size);
      stream.next(m.vague_search);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gettrajectorylist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Gettrajectorylist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Gettrajectorylist_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "page_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.page_num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "page_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.page_size);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vague_search: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.vague_search);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_GETTRAJECTORYLIST_H
