// Generated by gencpp from file rm_msgs/Hand_Seq.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_HAND_SEQ_H
#define RM_MSGS_MESSAGE_HAND_SEQ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Hand_Seq_
{
  typedef Hand_Seq_<ContainerAllocator> Type;

  Hand_Seq_()
    : seq_num(0)
    , block(false)  {
    }
  Hand_Seq_(const ContainerAllocator& _alloc)
    : seq_num(0)
    , block(false)  {
  (void)_alloc;
    }



   typedef uint16_t _seq_num_type;
  _seq_num_type seq_num;

   typedef uint8_t _block_type;
  _block_type block;





  typedef boost::shared_ptr< ::rm_msgs::Hand_Seq_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Hand_Seq_<ContainerAllocator> const> ConstPtr;

}; // struct Hand_Seq_

typedef ::rm_msgs::Hand_Seq_<std::allocator<void> > Hand_Seq;

typedef boost::shared_ptr< ::rm_msgs::Hand_Seq > Hand_SeqPtr;
typedef boost::shared_ptr< ::rm_msgs::Hand_Seq const> Hand_SeqConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Hand_Seq_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Hand_Seq_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Hand_Seq_<ContainerAllocator1> & lhs, const ::rm_msgs::Hand_Seq_<ContainerAllocator2> & rhs)
{
  return lhs.seq_num == rhs.seq_num &&
    lhs.block == rhs.block;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Hand_Seq_<ContainerAllocator1> & lhs, const ::rm_msgs::Hand_Seq_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Hand_Seq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Hand_Seq_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Hand_Seq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Hand_Seq_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Hand_Seq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Hand_Seq_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Hand_Seq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f00b164e44237e7253d6d77c16c73f25";
  }

  static const char* value(const ::rm_msgs::Hand_Seq_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf00b164e44237e72ULL;
  static const uint64_t static_value2 = 0x53d6d77c16c73f25ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Hand_Seq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Hand_Seq";
  }

  static const char* value(const ::rm_msgs::Hand_Seq_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Hand_Seq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#设置灵巧手动作序列\n"
"uint16 seq_num         #预先保存在灵巧手内的序列序号，范围：1~40\n"
"bool block #true 表示阻塞模式，false 表示非阻塞模式。\n"
;
  }

  static const char* value(const ::rm_msgs::Hand_Seq_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Hand_Seq_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seq_num);
      stream.next(m.block);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Hand_Seq_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Hand_Seq_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Hand_Seq_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "seq_num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.seq_num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "block: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_HAND_SEQ_H
