// Generated by gencpp from file rm_msgs/Jointversion.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_JOINTVERSION_H
#define RM_MSGS_MESSAGE_JOINTVERSION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Jointversion_
{
  typedef Jointversion_<ContainerAllocator> Type;

  Jointversion_()
    : joint_version()  {
    }
  Jointversion_(const ContainerAllocator& _alloc)
    : joint_version()  {
      joint_version.assign(std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>(_alloc));
  }



   typedef boost::array<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, 7>  _joint_version_type;
  _joint_version_type joint_version;





  typedef boost::shared_ptr< ::rm_msgs::Jointversion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Jointversion_<ContainerAllocator> const> ConstPtr;

}; // struct Jointversion_

typedef ::rm_msgs::Jointversion_<std::allocator<void> > Jointversion;

typedef boost::shared_ptr< ::rm_msgs::Jointversion > JointversionPtr;
typedef boost::shared_ptr< ::rm_msgs::Jointversion const> JointversionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Jointversion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Jointversion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Jointversion_<ContainerAllocator1> & lhs, const ::rm_msgs::Jointversion_<ContainerAllocator2> & rhs)
{
  return lhs.joint_version == rhs.joint_version;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Jointversion_<ContainerAllocator1> & lhs, const ::rm_msgs::Jointversion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Jointversion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Jointversion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Jointversion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Jointversion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Jointversion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Jointversion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Jointversion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34fe8048af36c99d06616a2279b77cd6";
  }

  static const char* value(const ::rm_msgs::Jointversion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34fe8048af36c99dULL;
  static const uint64_t static_value2 = 0x06616a2279b77cd6ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Jointversion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Jointversion";
  }

  static const char* value(const ::rm_msgs::Jointversion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Jointversion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[7] joint_version\n"
;
  }

  static const char* value(const ::rm_msgs::Jointversion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Jointversion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Jointversion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Jointversion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Jointversion_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint_version: ";
    if (v.joint_version.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_version.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.joint_version[i]);
    }
    if (v.joint_version.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_JOINTVERSION_H
