// Generated by gencpp from file rm_msgs/Mastername.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_MASTERNAME_H
#define RM_MSGS_MESSAGE_MASTERNAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Mastername_
{
  typedef Mastername_<ContainerAllocator> Type;

  Mastername_()
    : master_name()  {
    }
  Mastername_(const ContainerAllocator& _alloc)
    : master_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _master_name_type;
  _master_name_type master_name;





  typedef boost::shared_ptr< ::rm_msgs::Mastername_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Mastername_<ContainerAllocator> const> ConstPtr;

}; // struct Mastername_

typedef ::rm_msgs::Mastername_<std::allocator<void> > Mastername;

typedef boost::shared_ptr< ::rm_msgs::Mastername > MasternamePtr;
typedef boost::shared_ptr< ::rm_msgs::Mastername const> MasternameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Mastername_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Mastername_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Mastername_<ContainerAllocator1> & lhs, const ::rm_msgs::Mastername_<ContainerAllocator2> & rhs)
{
  return lhs.master_name == rhs.master_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Mastername_<ContainerAllocator1> & lhs, const ::rm_msgs::Mastername_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Mastername_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Mastername_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Mastername_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Mastername_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Mastername_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Mastername_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Mastername_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85cc930e49a075f3a896b60d7598ba17";
  }

  static const char* value(const ::rm_msgs::Mastername_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85cc930e49a075f3ULL;
  static const uint64_t static_value2 = 0xa896b60d7598ba17ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Mastername_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Mastername";
  }

  static const char* value(const ::rm_msgs::Mastername_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Mastername_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string master_name\n"
;
  }

  static const char* value(const ::rm_msgs::Mastername_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Mastername_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.master_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mastername_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Mastername_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Mastername_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "master_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.master_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_MASTERNAME_H
