// Generated by gencpp from file rm_msgs/Modbustcpmasterinfo.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_MODBUSTCPMASTERINFO_H
#define RM_MSGS_MESSAGE_MODBUSTCPMASTERINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Modbustcpmasterinfo_
{
  typedef Modbustcpmasterinfo_<ContainerAllocator> Type;

  Modbustcpmasterinfo_()
    : master_name()
    , ip()
    , port(0)  {
    }
  Modbustcpmasterinfo_(const ContainerAllocator& _alloc)
    : master_name(_alloc)
    , ip(_alloc)
    , port(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _master_name_type;
  _master_name_type master_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ip_type;
  _ip_type ip;

   typedef int32_t _port_type;
  _port_type port;





  typedef boost::shared_ptr< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> const> ConstPtr;

}; // struct Modbustcpmasterinfo_

typedef ::rm_msgs::Modbustcpmasterinfo_<std::allocator<void> > Modbustcpmasterinfo;

typedef boost::shared_ptr< ::rm_msgs::Modbustcpmasterinfo > ModbustcpmasterinfoPtr;
typedef boost::shared_ptr< ::rm_msgs::Modbustcpmasterinfo const> ModbustcpmasterinfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator1> & lhs, const ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator2> & rhs)
{
  return lhs.master_name == rhs.master_name &&
    lhs.ip == rhs.ip &&
    lhs.port == rhs.port;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator1> & lhs, const ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5135e7787693648e691b7b714a55fa9e";
  }

  static const char* value(const ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5135e7787693648eULL;
  static const uint64_t static_value2 = 0x691b7b714a55fa9eULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Modbustcpmasterinfo";
  }

  static const char* value(const ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string master_name # Modbus 主站名称，最大长度15个字符\n"
"string ip          # TCP主站 IP 地址\n"
"int32 port         # TCP主站端口号	\n"
;
  }

  static const char* value(const ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.master_name);
      stream.next(m.ip);
      stream.next(m.port);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Modbustcpmasterinfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "master_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.master_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ip);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "port: ";
    Printer<int32_t>::stream(s, indent + "  ", v.port);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_MODBUSTCPMASTERINFO_H
