// Generated by gencpp from file rm_msgs/Modbustcpmasterlist.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_MODBUSTCPMASTERLIST_H
#define RM_MSGS_MESSAGE_MODBUSTCPMASTERLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rm_msgs/Modbustcpmasterinfo.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct Modbustcpmasterlist_
{
  typedef Modbustcpmasterlist_<ContainerAllocator> Type;

  Modbustcpmasterlist_()
    : master_list()  {
    }
  Modbustcpmasterlist_(const ContainerAllocator& _alloc)
    : master_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >> _master_list_type;
  _master_list_type master_list;





  typedef boost::shared_ptr< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> const> ConstPtr;

}; // struct Modbustcpmasterlist_

typedef ::rm_msgs::Modbustcpmasterlist_<std::allocator<void> > Modbustcpmasterlist;

typedef boost::shared_ptr< ::rm_msgs::Modbustcpmasterlist > ModbustcpmasterlistPtr;
typedef boost::shared_ptr< ::rm_msgs::Modbustcpmasterlist const> ModbustcpmasterlistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator1> & lhs, const ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator2> & rhs)
{
  return lhs.master_list == rhs.master_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator1> & lhs, const ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b8086f234a37bbe3de0d031d6dca80f";
  }

  static const char* value(const ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b8086f234a37bbeULL;
  static const uint64_t static_value2 = 0x3de0d031d6dca80fULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Modbustcpmasterlist";
  }

  static const char* value(const ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Modbustcpmasterinfo[] master_list   # 返回符合的TCP主站列表\n"
"\n"
"================================================================================\n"
"MSG: rm_msgs/Modbustcpmasterinfo\n"
"string master_name # Modbus 主站名称，最大长度15个字符\n"
"string ip          # TCP主站 IP 地址\n"
"int32 port         # TCP主站端口号	\n"
;
  }

  static const char* value(const ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.master_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Modbustcpmasterlist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Modbustcpmasterlist_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "master_list: ";
    if (v.master_list.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.master_list.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::rm_msgs::Modbustcpmasterinfo_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.master_list[i]);
    }
    if (v.master_list.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_MODBUSTCPMASTERLIST_H
