// Generated by gencpp from file rm_msgs/Modbusreaddata.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_MODBUSREADDATA_H
#define RM_MSGS_MESSAGE_MODBUSREADDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Modbusreaddata_
{
  typedef Modbusreaddata_<ContainerAllocator> Type;

  Modbusreaddata_()
    : read_data()  {
    }
  Modbusreaddata_(const ContainerAllocator& _alloc)
    : read_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _read_data_type;
  _read_data_type read_data;





  typedef boost::shared_ptr< ::rm_msgs::Modbusreaddata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Modbusreaddata_<ContainerAllocator> const> ConstPtr;

}; // struct Modbusreaddata_

typedef ::rm_msgs::Modbusreaddata_<std::allocator<void> > Modbusreaddata;

typedef boost::shared_ptr< ::rm_msgs::Modbusreaddata > ModbusreaddataPtr;
typedef boost::shared_ptr< ::rm_msgs::Modbusreaddata const> ModbusreaddataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Modbusreaddata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Modbusreaddata_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Modbusreaddata_<ContainerAllocator1> & lhs, const ::rm_msgs::Modbusreaddata_<ContainerAllocator2> & rhs)
{
  return lhs.read_data == rhs.read_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Modbusreaddata_<ContainerAllocator1> & lhs, const ::rm_msgs::Modbusreaddata_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Modbusreaddata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Modbusreaddata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Modbusreaddata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Modbusreaddata_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Modbusreaddata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Modbusreaddata_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Modbusreaddata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85133f00e9641b3d842dc178852ca264";
  }

  static const char* value(const ::rm_msgs::Modbusreaddata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85133f00e9641b3dULL;
  static const uint64_t static_value2 = 0x842dc178852ca264ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Modbusreaddata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Modbusreaddata";
  }

  static const char* value(const ::rm_msgs::Modbusreaddata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Modbusreaddata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] read_data\n"
;
  }

  static const char* value(const ::rm_msgs::Modbusreaddata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Modbusreaddata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.read_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Modbusreaddata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Modbusreaddata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Modbusreaddata_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "read_data: ";
    if (v.read_data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.read_data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.read_data[i]);
    }
    if (v.read_data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_MODBUSREADDATA_H
