// Generated by gencpp from file rm_msgs/Moveloffset.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_MOVELOFFSET_H
#define RM_MSGS_MESSAGE_MOVELOFFSET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct Moveloffset_
{
  typedef Moveloffset_<ContainerAllocator> Type;

  Moveloffset_()
    : offset()
    , speed(0)
    , r(0)
    , trajectory_connect(false)
    , frame_type(false)
    , block(false)  {
    }
  Moveloffset_(const ContainerAllocator& _alloc)
    : offset(_alloc)
    , speed(0)
    , r(0)
    , trajectory_connect(false)
    , frame_type(false)
    , block(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _offset_type;
  _offset_type offset;

   typedef int32_t _speed_type;
  _speed_type speed;

   typedef int32_t _r_type;
  _r_type r;

   typedef uint8_t _trajectory_connect_type;
  _trajectory_connect_type trajectory_connect;

   typedef uint8_t _frame_type_type;
  _frame_type_type frame_type;

   typedef uint8_t _block_type;
  _block_type block;





  typedef boost::shared_ptr< ::rm_msgs::Moveloffset_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Moveloffset_<ContainerAllocator> const> ConstPtr;

}; // struct Moveloffset_

typedef ::rm_msgs::Moveloffset_<std::allocator<void> > Moveloffset;

typedef boost::shared_ptr< ::rm_msgs::Moveloffset > MoveloffsetPtr;
typedef boost::shared_ptr< ::rm_msgs::Moveloffset const> MoveloffsetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Moveloffset_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Moveloffset_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Moveloffset_<ContainerAllocator1> & lhs, const ::rm_msgs::Moveloffset_<ContainerAllocator2> & rhs)
{
  return lhs.offset == rhs.offset &&
    lhs.speed == rhs.speed &&
    lhs.r == rhs.r &&
    lhs.trajectory_connect == rhs.trajectory_connect &&
    lhs.frame_type == rhs.frame_type &&
    lhs.block == rhs.block;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Moveloffset_<ContainerAllocator1> & lhs, const ::rm_msgs::Moveloffset_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Moveloffset_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Moveloffset_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Moveloffset_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Moveloffset_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Moveloffset_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Moveloffset_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Moveloffset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af2efa1aef4c53564271cdf8a17ca144";
  }

  static const char* value(const ::rm_msgs::Moveloffset_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf2efa1aef4c5356ULL;
  static const uint64_t static_value2 = 0x4271cdf8a17ca144ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Moveloffset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Moveloffset";
  }

  static const char* value(const ::rm_msgs::Moveloffset_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Moveloffset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose offset\n"
"int32 speed\n"
"int32 r\n"
"bool trajectory_connect\n"
"bool frame_type\n"
"bool block\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rm_msgs::Moveloffset_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Moveloffset_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offset);
      stream.next(m.speed);
      stream.next(m.r);
      stream.next(m.trajectory_connect);
      stream.next(m.frame_type);
      stream.next(m.block);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Moveloffset_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Moveloffset_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Moveloffset_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "offset: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.offset);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "r: ";
    Printer<int32_t>::stream(s, indent + "  ", v.r);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory_connect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trajectory_connect);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "frame_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frame_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "block: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_MOVELOFFSET_H
