// Generated by gencpp from file rm_msgs/Programrunstate.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_PROGRAMRUNSTATE_H
#define RM_MSGS_MESSAGE_PROGRAMRUNSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Programrunstate_
{
  typedef Programrunstate_<ContainerAllocator> Type;

  Programrunstate_()
    : run_state(0)
    , id(0)
    , edit_id(0)
    , plan_num(0)
    , total_loop(0)
    , step_mode(0)
    , plan_speed(0)
    , loop_num()
    , loop_cont()  {
    }
  Programrunstate_(const ContainerAllocator& _alloc)
    : run_state(0)
    , id(0)
    , edit_id(0)
    , plan_num(0)
    , total_loop(0)
    , step_mode(0)
    , plan_speed(0)
    , loop_num(_alloc)
    , loop_cont(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _run_state_type;
  _run_state_type run_state;

   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _edit_id_type;
  _edit_id_type edit_id;

   typedef int32_t _plan_num_type;
  _plan_num_type plan_num;

   typedef int32_t _total_loop_type;
  _total_loop_type total_loop;

   typedef int32_t _step_mode_type;
  _step_mode_type step_mode;

   typedef int32_t _plan_speed_type;
  _plan_speed_type plan_speed;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _loop_num_type;
  _loop_num_type loop_num;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _loop_cont_type;
  _loop_cont_type loop_cont;





  typedef boost::shared_ptr< ::rm_msgs::Programrunstate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Programrunstate_<ContainerAllocator> const> ConstPtr;

}; // struct Programrunstate_

typedef ::rm_msgs::Programrunstate_<std::allocator<void> > Programrunstate;

typedef boost::shared_ptr< ::rm_msgs::Programrunstate > ProgramrunstatePtr;
typedef boost::shared_ptr< ::rm_msgs::Programrunstate const> ProgramrunstateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Programrunstate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Programrunstate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Programrunstate_<ContainerAllocator1> & lhs, const ::rm_msgs::Programrunstate_<ContainerAllocator2> & rhs)
{
  return lhs.run_state == rhs.run_state &&
    lhs.id == rhs.id &&
    lhs.edit_id == rhs.edit_id &&
    lhs.plan_num == rhs.plan_num &&
    lhs.total_loop == rhs.total_loop &&
    lhs.step_mode == rhs.step_mode &&
    lhs.plan_speed == rhs.plan_speed &&
    lhs.loop_num == rhs.loop_num &&
    lhs.loop_cont == rhs.loop_cont;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Programrunstate_<ContainerAllocator1> & lhs, const ::rm_msgs::Programrunstate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Programrunstate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Programrunstate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Programrunstate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Programrunstate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Programrunstate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Programrunstate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Programrunstate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f985b60b566dc245fe01afe38654a230";
  }

  static const char* value(const ::rm_msgs::Programrunstate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf985b60b566dc245ULL;
  static const uint64_t static_value2 = 0xfe01afe38654a230ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Programrunstate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Programrunstate";
  }

  static const char* value(const ::rm_msgs::Programrunstate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Programrunstate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 run_state   # 运行状态 0 未开始 1运行中 2暂停中\n"
"int32 id          # 运行轨迹编号\n"
"int32 edit_id     # 上次编辑的在线编程编号 id\n"
"int32 plan_num    # 运行行数\n"
"int32 total_loop      # 循环指令数量\n"
"int32 step_mode       # 单步模式，1 为单步模式，0 为非单步模式\n"
"int32 plan_speed      # 全局规划速度比例 1-100\n"
"int32[] loop_num        # 循环行数\n"
"int32[] loop_cont       # 对应循环次数\n"
;
  }

  static const char* value(const ::rm_msgs::Programrunstate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Programrunstate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.run_state);
      stream.next(m.id);
      stream.next(m.edit_id);
      stream.next(m.plan_num);
      stream.next(m.total_loop);
      stream.next(m.step_mode);
      stream.next(m.plan_speed);
      stream.next(m.loop_num);
      stream.next(m.loop_cont);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Programrunstate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Programrunstate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Programrunstate_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "run_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.run_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "edit_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.edit_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "plan_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.plan_num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_loop: ";
    Printer<int32_t>::stream(s, indent + "  ", v.total_loop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "step_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.step_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "plan_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.plan_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "loop_num: ";
    if (v.loop_num.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.loop_num.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.loop_num[i]);
    }
    if (v.loop_num.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "loop_cont: ";
    if (v.loop_cont.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.loop_cont.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.loop_cont[i]);
    }
    if (v.loop_cont.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_PROGRAMRUNSTATE_H
