// Generated by gencpp from file rm_msgs/Read_ModbusRTU.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_READ_MODBUSRTU_H
#define RM_MSGS_MESSAGE_READ_MODBUSRTU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Read_ModbusRTU_
{
  typedef Read_ModbusRTU_<ContainerAllocator> Type;

  Read_ModbusRTU_()
    : address(0)
    , device(0)
    , num(0)
    , type(0)  {
    }
  Read_ModbusRTU_(const ContainerAllocator& _alloc)
    : address(0)
    , device(0)
    , num(0)
    , type(0)  {
  (void)_alloc;
    }



   typedef int32_t _address_type;
  _address_type address;

   typedef int32_t _device_type;
  _device_type device;

   typedef int32_t _num_type;
  _num_type num;

   typedef int32_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> const> ConstPtr;

}; // struct Read_ModbusRTU_

typedef ::rm_msgs::Read_ModbusRTU_<std::allocator<void> > Read_ModbusRTU;

typedef boost::shared_ptr< ::rm_msgs::Read_ModbusRTU > Read_ModbusRTUPtr;
typedef boost::shared_ptr< ::rm_msgs::Read_ModbusRTU const> Read_ModbusRTUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Read_ModbusRTU_<ContainerAllocator1> & lhs, const ::rm_msgs::Read_ModbusRTU_<ContainerAllocator2> & rhs)
{
  return lhs.address == rhs.address &&
    lhs.device == rhs.device &&
    lhs.num == rhs.num &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Read_ModbusRTU_<ContainerAllocator1> & lhs, const ::rm_msgs::Read_ModbusRTU_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58a66370687b1c7bdeac52f168ac52f1";
  }

  static const char* value(const ::rm_msgs::Read_ModbusRTU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58a66370687b1c7bULL;
  static const uint64_t static_value2 = 0xdeac52f168ac52f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Read_ModbusRTU";
  }

  static const char* value(const ::rm_msgs::Read_ModbusRTU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 address #线圈起始地址。\n"
"int32 device #外设设备地址。\n"
"int32 num #线圈数量。\n"
"int32 type #0-控制器端modbus主机；1-工具端modbus主机。\n"
;
  }

  static const char* value(const ::rm_msgs::Read_ModbusRTU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.device);
      stream.next(m.num);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Read_ModbusRTU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Read_ModbusRTU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Read_ModbusRTU_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "address: ";
    Printer<int32_t>::stream(s, indent + "  ", v.address);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device: ";
    Printer<int32_t>::stream(s, indent + "  ", v.device);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_READ_MODBUSRTU_H
