// Generated by gencpp from file rm_msgs/Read_TCPandRTU.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_READ_TCPANDRTU_H
#define RM_MSGS_MESSAGE_READ_TCPANDRTU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Read_TCPandRTU_
{
  typedef Read_TCPandRTU_<ContainerAllocator> Type;

  Read_TCPandRTU_()
    : address(0)
    , num(0)
    , ip()
    , port(0)
    , master_name()
    , device(0)
    , type(0)  {
    }
  Read_TCPandRTU_(const ContainerAllocator& _alloc)
    : address(0)
    , num(0)
    , ip(_alloc)
    , port(0)
    , master_name(_alloc)
    , device(0)
    , type(0)  {
  (void)_alloc;
    }



   typedef int32_t _address_type;
  _address_type address;

   typedef int32_t _num_type;
  _num_type num;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ip_type;
  _ip_type ip;

   typedef int32_t _port_type;
  _port_type port;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _master_name_type;
  _master_name_type master_name;

   typedef int32_t _device_type;
  _device_type device;

   typedef int32_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> const> ConstPtr;

}; // struct Read_TCPandRTU_

typedef ::rm_msgs::Read_TCPandRTU_<std::allocator<void> > Read_TCPandRTU;

typedef boost::shared_ptr< ::rm_msgs::Read_TCPandRTU > Read_TCPandRTUPtr;
typedef boost::shared_ptr< ::rm_msgs::Read_TCPandRTU const> Read_TCPandRTUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Read_TCPandRTU_<ContainerAllocator1> & lhs, const ::rm_msgs::Read_TCPandRTU_<ContainerAllocator2> & rhs)
{
  return lhs.address == rhs.address &&
    lhs.num == rhs.num &&
    lhs.ip == rhs.ip &&
    lhs.port == rhs.port &&
    lhs.master_name == rhs.master_name &&
    lhs.device == rhs.device &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Read_TCPandRTU_<ContainerAllocator1> & lhs, const ::rm_msgs::Read_TCPandRTU_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90a88b29976390e1b70c71f43af18e9c";
  }

  static const char* value(const ::rm_msgs::Read_TCPandRTU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90a88b29976390e1ULL;
  static const uint64_t static_value2 = 0xb70c71f43af18e9cULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Read_TCPandRTU";
  }

  static const char* value(const ::rm_msgs::Read_TCPandRTU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 address\n"
"int32 num\n"
"string ip\n"
"int32 port\n"
"string master_name\n"
"int32 device #外设设备地址。\n"
"int32 type #0-控制器端modbus主机；1-工具端modbus主机。3-TCP模式\n"
;
  }

  static const char* value(const ::rm_msgs::Read_TCPandRTU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.num);
      stream.next(m.ip);
      stream.next(m.port);
      stream.next(m.master_name);
      stream.next(m.device);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Read_TCPandRTU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Read_TCPandRTU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Read_TCPandRTU_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "address: ";
    Printer<int32_t>::stream(s, indent + "  ", v.address);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ip);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "port: ";
    Printer<int32_t>::stream(s, indent + "  ", v.port);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "master_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.master_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device: ";
    Printer<int32_t>::stream(s, indent + "  ", v.device);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_READ_TCPANDRTU_H
