// Generated by gencpp from file rm_msgs/RS485params.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RS485PARAMS_H
#define RM_MSGS_MESSAGE_RS485PARAMS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RS485params_
{
  typedef RS485params_<ContainerAllocator> Type;

  RS485params_()
    : mode(0)
    , baudrate(0)  {
    }
  RS485params_(const ContainerAllocator& _alloc)
    : mode(0)
    , baudrate(0)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;

   typedef int32_t _baudrate_type;
  _baudrate_type baudrate;





  typedef boost::shared_ptr< ::rm_msgs::RS485params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RS485params_<ContainerAllocator> const> ConstPtr;

}; // struct RS485params_

typedef ::rm_msgs::RS485params_<std::allocator<void> > RS485params;

typedef boost::shared_ptr< ::rm_msgs::RS485params > RS485paramsPtr;
typedef boost::shared_ptr< ::rm_msgs::RS485params const> RS485paramsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RS485params_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RS485params_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RS485params_<ContainerAllocator1> & lhs, const ::rm_msgs::RS485params_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.baudrate == rhs.baudrate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RS485params_<ContainerAllocator1> & lhs, const ::rm_msgs::RS485params_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RS485params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RS485params_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RS485params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RS485params_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RS485params_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RS485params_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RS485params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78bc9e6cebd1458721f892a614d5c54c";
  }

  static const char* value(const ::rm_msgs::RS485params_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78bc9e6cebd14587ULL;
  static const uint64_t static_value2 = 0x21f892a614d5c54cULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RS485params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RS485params";
  }

  static const char* value(const ::rm_msgs::RS485params_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RS485params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode\n"
"int32 baudrate\n"
;
  }

  static const char* value(const ::rm_msgs::RS485params_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RS485params_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.baudrate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RS485params_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RS485params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RS485params_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "baudrate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.baudrate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RS485PARAMS_H
