// Generated by gencpp from file rm_msgs/Softwarebuildinfo.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_SOFTWAREBUILDINFO_H
#define RM_MSGS_MESSAGE_SOFTWAREBUILDINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Softwarebuildinfo_
{
  typedef Softwarebuildinfo_<ContainerAllocator> Type;

  Softwarebuildinfo_()
    : build_time()
    , version()  {
    }
  Softwarebuildinfo_(const ContainerAllocator& _alloc)
    : build_time(_alloc)
    , version(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _build_time_type;
  _build_time_type build_time;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _version_type;
  _version_type version;





  typedef boost::shared_ptr< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> const> ConstPtr;

}; // struct Softwarebuildinfo_

typedef ::rm_msgs::Softwarebuildinfo_<std::allocator<void> > Softwarebuildinfo;

typedef boost::shared_ptr< ::rm_msgs::Softwarebuildinfo > SoftwarebuildinfoPtr;
typedef boost::shared_ptr< ::rm_msgs::Softwarebuildinfo const> SoftwarebuildinfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Softwarebuildinfo_<ContainerAllocator1> & lhs, const ::rm_msgs::Softwarebuildinfo_<ContainerAllocator2> & rhs)
{
  return lhs.build_time == rhs.build_time &&
    lhs.version == rhs.version;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Softwarebuildinfo_<ContainerAllocator1> & lhs, const ::rm_msgs::Softwarebuildinfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7075122606129dab433ee6c359a4c404";
  }

  static const char* value(const ::rm_msgs::Softwarebuildinfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7075122606129dabULL;
  static const uint64_t static_value2 = 0x433ee6c359a4c404ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Softwarebuildinfo";
  }

  static const char* value(const ::rm_msgs::Softwarebuildinfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string build_time\n"
"string version\n"
;
  }

  static const char* value(const ::rm_msgs::Softwarebuildinfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.build_time);
      stream.next(m.version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Softwarebuildinfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Softwarebuildinfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Softwarebuildinfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "build_time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.build_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_SOFTWAREBUILDINFO_H
