// Generated by gencpp from file rm_msgs/Start_Multi_Drag_Teach.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_START_MULTI_DRAG_TEACH_H
#define RM_MSGS_MESSAGE_START_MULTI_DRAG_TEACH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Start_Multi_Drag_Teach_
{
  typedef Start_Multi_Drag_Teach_<ContainerAllocator> Type;

  Start_Multi_Drag_Teach_()
    : free_axes()
    , frame(0)
    , singular_wall(0)  {
      free_axes.assign(0);
  }
  Start_Multi_Drag_Teach_(const ContainerAllocator& _alloc)
    : free_axes()
    , frame(0)
    , singular_wall(0)  {
  (void)_alloc;
      free_axes.assign(0);
  }



   typedef boost::array<int32_t, 6>  _free_axes_type;
  _free_axes_type free_axes;

   typedef int32_t _frame_type;
  _frame_type frame;

   typedef int32_t _singular_wall_type;
  _singular_wall_type singular_wall;





  typedef boost::shared_ptr< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> const> ConstPtr;

}; // struct Start_Multi_Drag_Teach_

typedef ::rm_msgs::Start_Multi_Drag_Teach_<std::allocator<void> > Start_Multi_Drag_Teach;

typedef boost::shared_ptr< ::rm_msgs::Start_Multi_Drag_Teach > Start_Multi_Drag_TeachPtr;
typedef boost::shared_ptr< ::rm_msgs::Start_Multi_Drag_Teach const> Start_Multi_Drag_TeachConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator1> & lhs, const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator2> & rhs)
{
  return lhs.free_axes == rhs.free_axes &&
    lhs.frame == rhs.frame &&
    lhs.singular_wall == rhs.singular_wall;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator1> & lhs, const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36a7e83e1c20d27bf9d63d9ab11797e1";
  }

  static const char* value(const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36a7e83e1c20d27bULL;
  static const uint64_t static_value2 = 0xf9d63d9ab11797e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Start_Multi_Drag_Teach";
  }

  static const char* value(const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#uint8 mode\n"
"int32[6] free_axes       # 自由驱动方向[x,y,z,rx,ry,rz]，0-在参考坐标系对应方向轴上不可拖动，1-在参考坐标系对应方向轴上可拖动\n"
"int32 frame              # 参考坐标系，0-工作坐标系 1-工具坐标系。\n"
"int32 singular_wall      # 仅在六维力模式拖动示教中生效，用于指定是否开启拖动奇异墙，0表示关闭拖动奇异墙，1表示开启拖动奇异墙，若无配置参数，默认启动拖动奇异墙\n"
;
  }

  static const char* value(const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.free_axes);
      stream.next(m.frame);
      stream.next(m.singular_wall);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Start_Multi_Drag_Teach_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "free_axes: ";
    if (v.free_axes.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.free_axes.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.free_axes[i]);
    }
    if (v.free_axes.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "frame: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frame);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "singular_wall: ";
    Printer<int32_t>::stream(s, indent + "  ", v.singular_wall);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_START_MULTI_DRAG_TEACH_H
