// Generated by gencpp from file rm_msgs/Write_ModbusRTU.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_WRITE_MODBUSRTU_H
#define RM_MSGS_MESSAGE_WRITE_MODBUSRTU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Write_ModbusRTU_
{
  typedef Write_ModbusRTU_<ContainerAllocator> Type;

  Write_ModbusRTU_()
    : address(0)
    , data()
    , type(0)
    , device(0)  {
    }
  Write_ModbusRTU_(const ContainerAllocator& _alloc)
    : address(0)
    , data(_alloc)
    , type(0)
    , device(0)  {
  (void)_alloc;
    }



   typedef int32_t _address_type;
  _address_type address;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _data_type;
  _data_type data;

   typedef int32_t _type_type;
  _type_type type;

   typedef int32_t _device_type;
  _device_type device;





  typedef boost::shared_ptr< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> const> ConstPtr;

}; // struct Write_ModbusRTU_

typedef ::rm_msgs::Write_ModbusRTU_<std::allocator<void> > Write_ModbusRTU;

typedef boost::shared_ptr< ::rm_msgs::Write_ModbusRTU > Write_ModbusRTUPtr;
typedef boost::shared_ptr< ::rm_msgs::Write_ModbusRTU const> Write_ModbusRTUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Write_ModbusRTU_<ContainerAllocator1> & lhs, const ::rm_msgs::Write_ModbusRTU_<ContainerAllocator2> & rhs)
{
  return lhs.address == rhs.address &&
    lhs.data == rhs.data &&
    lhs.type == rhs.type &&
    lhs.device == rhs.device;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Write_ModbusRTU_<ContainerAllocator1> & lhs, const ::rm_msgs::Write_ModbusRTU_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af497b1a335cfca6101c39a0e6e4ca1a";
  }

  static const char* value(const ::rm_msgs::Write_ModbusRTU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf497b1a335cfca6ULL;
  static const uint64_t static_value2 = 0x101c39a0e6e4ca1aULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Write_ModbusRTU";
  }

  static const char* value(const ::rm_msgs::Write_ModbusRTU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 address\n"
"int32[] data\n"
"int32 type\n"
"int32 device\n"
;
  }

  static const char* value(const ::rm_msgs::Write_ModbusRTU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.data);
      stream.next(m.type);
      stream.next(m.device);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Write_ModbusRTU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Write_ModbusRTU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Write_ModbusRTU_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "address: ";
    Printer<int32_t>::stream(s, indent + "  ", v.address);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device: ";
    Printer<int32_t>::stream(s, indent + "  ", v.device);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_WRITE_MODBUSRTU_H
