// Generated by gencpp from file rm_msgs/Write_TCPandRTU.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_WRITE_TCPANDRTU_H
#define RM_MSGS_MESSAGE_WRITE_TCPANDRTU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Write_TCPandRTU_
{
  typedef Write_TCPandRTU_<ContainerAllocator> Type;

  Write_TCPandRTU_()
    : address(0)
    , data()
    , ip()
    , port(0)
    , master_name()
    , type(0)
    , device(0)  {
    }
  Write_TCPandRTU_(const ContainerAllocator& _alloc)
    : address(0)
    , data(_alloc)
    , ip(_alloc)
    , port(0)
    , master_name(_alloc)
    , type(0)
    , device(0)  {
  (void)_alloc;
    }



   typedef int32_t _address_type;
  _address_type address;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _data_type;
  _data_type data;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ip_type;
  _ip_type ip;

   typedef int32_t _port_type;
  _port_type port;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _master_name_type;
  _master_name_type master_name;

   typedef int32_t _type_type;
  _type_type type;

   typedef int32_t _device_type;
  _device_type device;





  typedef boost::shared_ptr< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> const> ConstPtr;

}; // struct Write_TCPandRTU_

typedef ::rm_msgs::Write_TCPandRTU_<std::allocator<void> > Write_TCPandRTU;

typedef boost::shared_ptr< ::rm_msgs::Write_TCPandRTU > Write_TCPandRTUPtr;
typedef boost::shared_ptr< ::rm_msgs::Write_TCPandRTU const> Write_TCPandRTUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Write_TCPandRTU_<ContainerAllocator1> & lhs, const ::rm_msgs::Write_TCPandRTU_<ContainerAllocator2> & rhs)
{
  return lhs.address == rhs.address &&
    lhs.data == rhs.data &&
    lhs.ip == rhs.ip &&
    lhs.port == rhs.port &&
    lhs.master_name == rhs.master_name &&
    lhs.type == rhs.type &&
    lhs.device == rhs.device;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Write_TCPandRTU_<ContainerAllocator1> & lhs, const ::rm_msgs::Write_TCPandRTU_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c74acded0fd8ce10898127e85288096e";
  }

  static const char* value(const ::rm_msgs::Write_TCPandRTU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc74acded0fd8ce10ULL;
  static const uint64_t static_value2 = 0x898127e85288096eULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Write_TCPandRTU";
  }

  static const char* value(const ::rm_msgs::Write_TCPandRTU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 address\n"
"int32[] data\n"
"string ip\n"
"int32 port\n"
"string master_name\n"
"int32 type\n"
"int32 device\n"
;
  }

  static const char* value(const ::rm_msgs::Write_TCPandRTU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.data);
      stream.next(m.ip);
      stream.next(m.port);
      stream.next(m.master_name);
      stream.next(m.type);
      stream.next(m.device);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Write_TCPandRTU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Write_TCPandRTU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Write_TCPandRTU_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "address: ";
    Printer<int32_t>::stream(s, indent + "  ", v.address);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ip);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "port: ";
    Printer<int32_t>::stream(s, indent + "  ", v.port);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "master_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.master_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device: ";
    Printer<int32_t>::stream(s, indent + "  ", v.device);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_WRITE_TCPANDRTU_H
