# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Arm_Software_Version.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_msgs.msg

class Arm_Software_Version(genpy.Message):
  _md5sum = "f90eb6551bbde202ac1756e5a3ee2f6d"
  _type = "rm_msgs/Arm_Software_Version"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string product_version
string algorithm_info
Softwarebuildinfo ctrl_info
string dynamic_info #3
Softwarebuildinfo plan_info #3
string controller_version #4
Softwarebuildinfo com_info #4
Softwarebuildinfo program_info #4
================================================================================
MSG: rm_msgs/Softwarebuildinfo
string build_time
string version"""
  __slots__ = ['product_version','algorithm_info','ctrl_info','dynamic_info','plan_info','controller_version','com_info','program_info']
  _slot_types = ['string','string','rm_msgs/Softwarebuildinfo','string','rm_msgs/Softwarebuildinfo','string','rm_msgs/Softwarebuildinfo','rm_msgs/Softwarebuildinfo']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       product_version,algorithm_info,ctrl_info,dynamic_info,plan_info,controller_version,com_info,program_info

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Arm_Software_Version, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.product_version is None:
        self.product_version = ''
      if self.algorithm_info is None:
        self.algorithm_info = ''
      if self.ctrl_info is None:
        self.ctrl_info = rm_msgs.msg.Softwarebuildinfo()
      if self.dynamic_info is None:
        self.dynamic_info = ''
      if self.plan_info is None:
        self.plan_info = rm_msgs.msg.Softwarebuildinfo()
      if self.controller_version is None:
        self.controller_version = ''
      if self.com_info is None:
        self.com_info = rm_msgs.msg.Softwarebuildinfo()
      if self.program_info is None:
        self.program_info = rm_msgs.msg.Softwarebuildinfo()
    else:
      self.product_version = ''
      self.algorithm_info = ''
      self.ctrl_info = rm_msgs.msg.Softwarebuildinfo()
      self.dynamic_info = ''
      self.plan_info = rm_msgs.msg.Softwarebuildinfo()
      self.controller_version = ''
      self.com_info = rm_msgs.msg.Softwarebuildinfo()
      self.program_info = rm_msgs.msg.Softwarebuildinfo()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.product_version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.algorithm_info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ctrl_info.build_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ctrl_info.version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.dynamic_info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.plan_info.build_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.plan_info.version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.controller_version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.com_info.build_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.com_info.version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.program_info.build_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.program_info.version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ctrl_info is None:
        self.ctrl_info = rm_msgs.msg.Softwarebuildinfo()
      if self.plan_info is None:
        self.plan_info = rm_msgs.msg.Softwarebuildinfo()
      if self.com_info is None:
        self.com_info = rm_msgs.msg.Softwarebuildinfo()
      if self.program_info is None:
        self.program_info = rm_msgs.msg.Softwarebuildinfo()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.product_version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.product_version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.algorithm_info = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.algorithm_info = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ctrl_info.build_time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ctrl_info.build_time = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ctrl_info.version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ctrl_info.version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dynamic_info = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dynamic_info = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.plan_info.build_time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.plan_info.build_time = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.plan_info.version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.plan_info.version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.controller_version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.controller_version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.com_info.build_time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.com_info.build_time = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.com_info.version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.com_info.version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.program_info.build_time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.program_info.build_time = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.program_info.version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.program_info.version = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.product_version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.algorithm_info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ctrl_info.build_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.ctrl_info.version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.dynamic_info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.plan_info.build_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.plan_info.version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.controller_version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.com_info.build_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.com_info.version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.program_info.build_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.program_info.version
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ctrl_info is None:
        self.ctrl_info = rm_msgs.msg.Softwarebuildinfo()
      if self.plan_info is None:
        self.plan_info = rm_msgs.msg.Softwarebuildinfo()
      if self.com_info is None:
        self.com_info = rm_msgs.msg.Softwarebuildinfo()
      if self.program_info is None:
        self.program_info = rm_msgs.msg.Softwarebuildinfo()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.product_version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.product_version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.algorithm_info = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.algorithm_info = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ctrl_info.build_time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ctrl_info.build_time = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ctrl_info.version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ctrl_info.version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dynamic_info = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dynamic_info = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.plan_info.build_time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.plan_info.build_time = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.plan_info.version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.plan_info.version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.controller_version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.controller_version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.com_info.build_time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.com_info.build_time = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.com_info.version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.com_info.version = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.program_info.build_time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.program_info.build_time = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.program_info.version = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.program_info.version = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
