# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/ExpandState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ExpandState(genpy.Message):
  _md5sum = "51186bb81aaa7ad5c549fa4631da2340"
  _type = "rm_msgs/ExpandState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool get_state
int16 pos	    #扩展关节角度，单位度，精度 0.001°
int16 err_flag	#驱动错误代码
uint16 en_flag	#扩展关节使能状态
uint16 current	#当前驱动电流，单位：mA，精度：1mA。
byte mode	    #当前扩展关节状态，0-空闲，1-正方向速度运动，2-正方向位置运动，3-负方向速度运动，4-负方向位置运动
uint16 joint_id	#扩展关节ID"""
  __slots__ = ['get_state','pos','err_flag','en_flag','current','mode','joint_id']
  _slot_types = ['bool','int16','int16','uint16','uint16','byte','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       get_state,pos,err_flag,en_flag,current,mode,joint_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ExpandState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.get_state is None:
        self.get_state = False
      if self.pos is None:
        self.pos = 0
      if self.err_flag is None:
        self.err_flag = 0
      if self.en_flag is None:
        self.en_flag = 0
      if self.current is None:
        self.current = 0
      if self.mode is None:
        self.mode = 0
      if self.joint_id is None:
        self.joint_id = 0
    else:
      self.get_state = False
      self.pos = 0
      self.err_flag = 0
      self.en_flag = 0
      self.current = 0
      self.mode = 0
      self.joint_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2h2HbH().pack(_x.get_state, _x.pos, _x.err_flag, _x.en_flag, _x.current, _x.mode, _x.joint_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.get_state, _x.pos, _x.err_flag, _x.en_flag, _x.current, _x.mode, _x.joint_id,) = _get_struct_B2h2HbH().unpack(str[start:end])
      self.get_state = bool(self.get_state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2h2HbH().pack(_x.get_state, _x.pos, _x.err_flag, _x.en_flag, _x.current, _x.mode, _x.joint_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.get_state, _x.pos, _x.err_flag, _x.en_flag, _x.current, _x.mode, _x.joint_id,) = _get_struct_B2h2HbH().unpack(str[start:end])
      self.get_state = bool(self.get_state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2h2HbH = None
def _get_struct_B2h2HbH():
    global _struct_B2h2HbH
    if _struct_B2h2HbH is None:
        _struct_B2h2HbH = struct.Struct("<B2h2HbH")
    return _struct_B2h2HbH
