# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Modbustcpmasterlist.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_msgs.msg

class Modbustcpmasterlist(genpy.Message):
  _md5sum = "4b8086f234a37bbe3de0d031d6dca80f"
  _type = "rm_msgs/Modbustcpmasterlist"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Modbustcpmasterinfo[] master_list   # 返回符合的TCP主站列表

================================================================================
MSG: rm_msgs/Modbustcpmasterinfo
string master_name # Modbus 主站名称，最大长度15个字符
string ip          # TCP主站 IP 地址
int32 port         # TCP主站端口号	"""
  __slots__ = ['master_list']
  _slot_types = ['rm_msgs/Modbustcpmasterinfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       master_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Modbustcpmasterlist, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.master_list is None:
        self.master_list = []
    else:
      self.master_list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.master_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.master_list:
        _x = val1.master_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.ip
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.port
        buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.master_list is None:
        self.master_list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.master_list = []
      for i in range(0, length):
        val1 = rm_msgs.msg.Modbustcpmasterinfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.master_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.master_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.ip = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.ip = str[start:end]
        start = end
        end += 4
        (val1.port,) = _get_struct_i().unpack(str[start:end])
        self.master_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.master_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.master_list:
        _x = val1.master_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.ip
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.port
        buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.master_list is None:
        self.master_list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.master_list = []
      for i in range(0, length):
        val1 = rm_msgs.msg.Modbustcpmasterinfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.master_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.master_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.ip = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.ip = str[start:end]
        start = end
        end += 4
        (val1.port,) = _get_struct_i().unpack(str[start:end])
        self.master_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
