# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Moveloffset.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Moveloffset(genpy.Message):
  _md5sum = "af2efa1aef4c53564271cdf8a17ca144"
  _type = "rm_msgs/Moveloffset"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose offset
int32 speed
int32 r
bool trajectory_connect
bool frame_type
bool block
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['offset','speed','r','trajectory_connect','frame_type','block']
  _slot_types = ['geometry_msgs/Pose','int32','int32','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       offset,speed,r,trajectory_connect,frame_type,block

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Moveloffset, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.offset is None:
        self.offset = geometry_msgs.msg.Pose()
      if self.speed is None:
        self.speed = 0
      if self.r is None:
        self.r = 0
      if self.trajectory_connect is None:
        self.trajectory_connect = False
      if self.frame_type is None:
        self.frame_type = False
      if self.block is None:
        self.block = False
    else:
      self.offset = geometry_msgs.msg.Pose()
      self.speed = 0
      self.r = 0
      self.trajectory_connect = False
      self.frame_type = False
      self.block = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d2i3B().pack(_x.offset.position.x, _x.offset.position.y, _x.offset.position.z, _x.offset.orientation.x, _x.offset.orientation.y, _x.offset.orientation.z, _x.offset.orientation.w, _x.speed, _x.r, _x.trajectory_connect, _x.frame_type, _x.block))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.offset is None:
        self.offset = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 67
      (_x.offset.position.x, _x.offset.position.y, _x.offset.position.z, _x.offset.orientation.x, _x.offset.orientation.y, _x.offset.orientation.z, _x.offset.orientation.w, _x.speed, _x.r, _x.trajectory_connect, _x.frame_type, _x.block,) = _get_struct_7d2i3B().unpack(str[start:end])
      self.trajectory_connect = bool(self.trajectory_connect)
      self.frame_type = bool(self.frame_type)
      self.block = bool(self.block)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d2i3B().pack(_x.offset.position.x, _x.offset.position.y, _x.offset.position.z, _x.offset.orientation.x, _x.offset.orientation.y, _x.offset.orientation.z, _x.offset.orientation.w, _x.speed, _x.r, _x.trajectory_connect, _x.frame_type, _x.block))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.offset is None:
        self.offset = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 67
      (_x.offset.position.x, _x.offset.position.y, _x.offset.position.z, _x.offset.orientation.x, _x.offset.orientation.y, _x.offset.orientation.z, _x.offset.orientation.w, _x.speed, _x.r, _x.trajectory_connect, _x.frame_type, _x.block,) = _get_struct_7d2i3B().unpack(str[start:end])
      self.trajectory_connect = bool(self.trajectory_connect)
      self.frame_type = bool(self.frame_type)
      self.block = bool(self.block)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d2i3B = None
def _get_struct_7d2i3B():
    global _struct_7d2i3B
    if _struct_7d2i3B is None:
        _struct_7d2i3B = struct.Struct("<7d2i3B")
    return _struct_7d2i3B
