# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Programrunstate.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Programrunstate(genpy.Message):
  _md5sum = "f985b60b566dc245fe01afe38654a230"
  _type = "rm_msgs/Programrunstate"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 run_state   # 运行状态 0 未开始 1运行中 2暂停中
int32 id          # 运行轨迹编号
int32 edit_id     # 上次编辑的在线编程编号 id
int32 plan_num    # 运行行数
int32 total_loop      # 循环指令数量
int32 step_mode       # 单步模式，1 为单步模式，0 为非单步模式
int32 plan_speed      # 全局规划速度比例 1-100
int32[] loop_num        # 循环行数
int32[] loop_cont       # 对应循环次数"""
  __slots__ = ['run_state','id','edit_id','plan_num','total_loop','step_mode','plan_speed','loop_num','loop_cont']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','int32[]','int32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       run_state,id,edit_id,plan_num,total_loop,step_mode,plan_speed,loop_num,loop_cont

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Programrunstate, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.run_state is None:
        self.run_state = 0
      if self.id is None:
        self.id = 0
      if self.edit_id is None:
        self.edit_id = 0
      if self.plan_num is None:
        self.plan_num = 0
      if self.total_loop is None:
        self.total_loop = 0
      if self.step_mode is None:
        self.step_mode = 0
      if self.plan_speed is None:
        self.plan_speed = 0
      if self.loop_num is None:
        self.loop_num = []
      if self.loop_cont is None:
        self.loop_cont = []
    else:
      self.run_state = 0
      self.id = 0
      self.edit_id = 0
      self.plan_num = 0
      self.total_loop = 0
      self.step_mode = 0
      self.plan_speed = 0
      self.loop_num = []
      self.loop_cont = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7i().pack(_x.run_state, _x.id, _x.edit_id, _x.plan_num, _x.total_loop, _x.step_mode, _x.plan_speed))
      length = len(self.loop_num)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.loop_num))
      length = len(self.loop_cont)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.loop_cont))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.run_state, _x.id, _x.edit_id, _x.plan_num, _x.total_loop, _x.step_mode, _x.plan_speed,) = _get_struct_7i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.loop_num = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.loop_cont = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7i().pack(_x.run_state, _x.id, _x.edit_id, _x.plan_num, _x.total_loop, _x.step_mode, _x.plan_speed))
      length = len(self.loop_num)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.loop_num.tostring())
      length = len(self.loop_cont)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.loop_cont.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.run_state, _x.id, _x.edit_id, _x.plan_num, _x.total_loop, _x.step_mode, _x.plan_speed,) = _get_struct_7i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.loop_num = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.loop_cont = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7i = None
def _get_struct_7i():
    global _struct_7i
    if _struct_7i is None:
        _struct_7i = struct.Struct("<7i")
    return _struct_7i
